### ISSUE TITLE
Issue with angular-timer version on bower

### ISSUE THREAD

**Issue by IvanGarzon** [siddii/angular-timer#186]
Hi Guys, Can you update the latest version in bower to be downloaded because the current version on bower is /*angular-timer - v1.3.1 - 2015-03-13 8:46 AM*/ and currently the latest version on git is /*angular-timer - v1.3.1 - 2015-05-19 12:41 AM*/, this would be great, thanks guys, amazing job....

**Comment by siddii** [comment]
I just pushed a new update - https://github.com/siddii/angular-timer/blob/eb043b1e5abd51a4c00b0b7504bfb5ed1ef8923a/dist/angular-timer.js

Can you please verify?

**Comment by IvanGarzon** [comment]
Hi @siddii thank you for getting back to me so quickly, but I just downloaded angular-timer from bower and I still getting /angular-timer - v1.3.1 - 2015-03-13 8:46 AM/ do perhaps you need to change the version's number to 1.3.2.....

**Comment by siddii** [comment]
I pushed a new release - https://github.com/siddii/angular-timer/releases/tag/v1.3.3

Hope this helps!

**Comment by IvanGarzon** [comment]
Thanks a lot @siddii Everything is solved.........
